/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.noldangGapseo;

public class Hello6 {

  public static void main(String[] args) {
    System.out.println("강동우입니다112412.");
  }
}
